# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_firewall_allow_services:
  - http
  - https
  - mysql

rhbase_firewall_allow_ports:
  - 9100/tcp # Prometheus
  - 9104/tcp # Container-exporter

rhbase_selinux_booleans:
  - httpd_can_network_connect_db