---
- name: Install docker yum repo
  yum_repository:
    name: docker
    description: docker repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/

- name: Make sure docker is installed
  package:
    name: docker-ce
    state: present

- name: Install docker-compose
  uri:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    creates: /usr/local/bin/docker-compose
    dest: /usr/local/bin/docker-compose
    mode: u=rwx,g=rx,o=rx

- name: Make sure docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: Make sure user vagrant is added to docker users
  user:
    name: vagrant
    append: yes
    groups: docker

- name: Pause playbook to prevent docker daemon error
  pause:
    minutes: 1

- name: Run docker-compose
  become: true
  become_user: vagrant
  shell: |
    docker-compose -f /vagrant/files/docker-compose-setup.yml up -d
    exit 0