# host_vars/lampstack.yml
---

rhbase_repositories:
  - epel-release

rhbase_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced
  - tcpdump

rhbase_firewall_allow_services:
  - http
  - https

mariadb_databases:
  - name: wordpress

mariadb_users:
  - name: wordpressusr
    password: BulpashCod
    priv: 'wordpress.*:ALL'

mariadb_root_password: Teilvadci

wordpress_database: wordpress
wordpress_user: wordpressusr
wordpress_password: BulpashCod
