# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_firewall_allow_services:
  - http
  - https
  - mysql

rhbase_firewall_allow_ports:
  - 3000/tcp
  - 3001/tcp
  - 9100/tcp
  - 9104/tcp
  
wtd_srv_docker_compose_package_state: present
wtd_srv_docker_group_users:
  - vagrant

wtd_srv_cockpit_web_package_state: "present"
wtd_srv_cockpit_web_dash_package_state: "present"
wtd_srv_cockpit_docker_package_state: "present"