# site.yml
---
- hosts: srv001
  become: true
  roles:
    - bertvv.rh-base
    - sepolicy
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
    - phpmyadmin
    - cloudalchemy.prometheus
    - cloudalchemy.grafana
    - cloudalchemy.node-exporter