version: '2.4'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
    volumes:
      - db-data:/var/lib/mysql

  wordpress:
    image: wordpress
    expose:
      - '80'
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mariadb
    scale: 3

  nginx:
    build: ./nginx
    depends_on:
      - wordpress
    ports:
      - 80:80

volumes:
  db-data:
  wp-data: